version: '3'

services:
  
  socket.subspace.seanmorr.is:
    build:
      context: ../
      dockerfile: vendor/seanmorris/subspace/infra/socker.Dockerfile
    image: socket.subspace.seanmorr.is
    restart: on-failure
    volumes:
      - ../:/app
