version: '3'

services:

  subspace.socket:
    build:
      context: ../
      dockerfile: infra/socket.Dockerfile
    image: seanmorris/subspace-socket
    restart: on-failure
    ports:
      - "9998:9998"
    volumes:
      - ../:/app

  subspace.web:
    build:
      context: ../
      dockerfile: infra/web.Dockerfile
    image: seanmorris/subspace-web
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../:/app
